spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
#如果该属性为NULL则在前端的json中不显示
  jackson:
    default-property-inclusion: non-null
  redis:
    host: 192.168.30.113
    port: 6379
server:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: D:\dev\source\diancan\log
#  file: D:\dev\source\diancan\log\sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  mpAppId: wxaa577a46b8f1dd3b
  mpAppSecret: 6e018c145122b379e947c8b0fc0611aa
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: https://jianlin.natapp4.cc
  wechatOpenAuthorize: https://jianlin.natapp4.cc
  sell: https://jianlin.natapp4.cc